# Generated by Django 5.1.2 on 2024-12-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_symbol", models.CharField(max_length=20)),
                ("heading", models.CharField(max_length=500)),
                ("full_story", models.TextField()),
                ("date", models.DateTimeField()),
                ("url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name_plural": "Stock News",
                "ordering": ["-date"],
            },
        ),
    ]
