# Generated by Django 5.1.2 on 2024-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_symbol", models.CharField(max_length=20)),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("price_summary", models.TextField()),
                ("news_summary", models.TextField()),
                ("sentiment_analysis", models.TextField()),
                ("investment_recommendation", models.TextField()),
                ("overall_score", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Stock Analyses",
                "ordering": ["-analysis_date"],
            },
        ),
    ]
